@baseUrl = http://localhost:5000
@urlPath= api/v1

POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials:true

{
 "userTo":"671e77be71b167afeef478b8",
  "postId":"671e75c2a41be93f8b1f2076",
  "comment":"happy",
  "profilePicture":"https://res/cloudinary.com/dozszgko7/image/upload/v1726384950/66e68b336718b32799d786e8"
}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/671e75c2a41be93f8b1f2076
Content-Type: application/json
Accept: application/json
withCredentials:true

{

}

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/671e75c2a41be93f8b1f2076/672474d1217d96684b0cb1bd
Content-Type: application/json
Accept: application/json
withCredentials:true

{}